name             'chef_rails_base'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef_rails_base'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'apt'
depends 'git'
depends 'user'
depends 'sudo'
depends 'locale'
depends 'nodejs', '~> 4.0.0'
depends 'memcached'
depends 'timezone_lwrp', '~> 0.1.10'
depends 'yarn'
depends 'zsh'
